export {default as Home } from './home/Home.js'
export {default as Contact} from './contact/Contact.js'
export {default as Login} from './auth/Login.js'
export {default as Register}  from './auth/Register.js'
export {default as Reset} from './auth/Reset.js'